version: 2
updates:
  # Enable version updates for npm (root only)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "arashin0209"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only security and patch updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Enable version updates for GitHub Actions  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 2
    assignees:
      - "arashin0209"