version: '3.8'

services:
  # Next.jsアプリケーション（開発用）
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_GOLD_PRICE_ID=${STRIPE_GOLD_PRICE_ID}
      - STRIPE_PLATINUM_PRICE_ID=${STRIPE_PLATINUM_PRICE_ID}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/.next
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL データベース（開発用）
  db:
    image: postgres:15-alpine
    container_name: product-base-postgres-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: product_base_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge
